nameApplication: API Gateway
hostApplication: http://localhost:3030

services:
  - nameRoute: /api/v1/tracking ## path name in proxy
    url: http://localhost:3031 ## host target
    routes:
      - path: /api/v1/tracking ## path target

  - nameRoute: /socket.io
    url: ws://localhost:4040
    routes:
      - path: /tracking
